name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
      - conda-cpp-build
      - conda-cpp-tests
      - conda-python-build
      - conda-python-cudf-tests
      - conda-python-other-tests
      - conda-java-tests
      - conda-notebook-tests
      - cudf-wheel-build
      - cudf-wheel-tests
      - dask-cudf-wheel-build
      - dask-cudf-wheel-tests
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/pr-builder.yaml@main
  checks:
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/checks.yaml@main
  conda-cpp-build:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-cpp-matrix-build.yaml@main
    with:
      build_type: pull-request
  conda-cpp-tests:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-cpp-tests.yaml@main
    with:
      build_type: pull-request
  conda-python-build:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-python-matrix-build.yaml@main
    with:
      build_type: pull-request
  conda-python-cudf-tests:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-python-tests.yaml@main
    with:
      build_type: pull-request
      test_script: "ci/test_python_cudf.sh"
  conda-python-other-tests:
    # Tests for dask_cudf, custreamz, cudf_kafka are separated for CI parallelism
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-python-tests.yaml@main
    with:
      build_type: pull-request
      test_script: "ci/test_python_other.sh"
  conda-java-tests:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@main
    with:
      build_type: pull-request
      node_type: "gpu-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci:latest"
      run_script: "ci/test_java.sh"
  conda-notebook-tests:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@main
    with:
      build_type: pull-request
      node_type: "gpu-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci:latest"
      run_script: "ci/test_notebooks.sh"
  cudf-wheel-build:
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-manylinux-build.yml@upkeep/manylinux-improvements
    with:
      build_type: pull-request
      package-dir: python/cudf
      package-name: cudf
      skbuild-configure-options: "-DCUDF_BUILD_WHEELS=ON -DDETECT_CONDA_ENV=OFF"
  cudf-wheel-tests:
    needs: cudf-wheel-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-manylinux-test.yml@upkeep/manylinux-improvements
    with:
      build_type: pull-request
      package-name: cudf
      test-before-arm64: "pip install tokenizers==0.10.2 cupy-cuda11x -f https://pip.cupy.dev/aarch64"
      test-unittest: "pytest -v -n 8 ./python/cudf/cudf/tests"
  dask-cudf-wheel-build:
    needs: cudf-wheel-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-pure-build.yml@upkeep/manylinux-improvements
    with:
      build_type: pull-request
      package-dir: python/dask_cudf
      package-name: dask_cudf
  dask-cudf-wheel-tests:
    needs: dask-cudf-wheel-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-pure-test.yml@upkeep/manylinux-improvements
    with:
      build_type: pull-request
      package-name: dask_cudf
      test-unittest: "pytest -v -n 8 ./python/dask_cudf/dask_cudf/tests"
